spring.application.name=momentum-api

spring.datasource.url=jdbc:postgresql://localhost:5432/momentum
spring.datasource.username=momentum
spring.datasource.password=momentum
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080