spring.application.name=momentum-api

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
momentum.cors.allowed-origins=${MOMENTUM_CORS_ALLOWED_ORIGINS}

server.port=8080

momentum.jwt.secret=${JWT_SECRET}
momentum.jwt.access-token-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS}
momentum.jwt.refresh-token-expiration-ms=${JWT_REFRESH_TOKEN_EXPIRATION_MS}
